### ISSUE TITLE
Transition

### ISSUE THREAD

**Issue by dandcg** [prasannavl/LiquidState#23]
Hey,

In stateless the a transition object is passed to the OnEntry/OnExit actions? You can use this to understand the previous state etc? In Liquid this doesn't seem to be the case - or am I missing something?

**Comment by prasannavl** [comment]
Interesting. I see how a transition object overload may be a useful addition. 

The best way to do that currently would be to use the state machine's `TransitionStarted`/`TransitionExecuted` events. They provide the transition objects. The idea at the moment is to keep the configurations (such as `OnEntry`, `OnExit`) completely oblivious to any of the machine's states.

**Comment by prasannavl** [comment]
Added new commit: 
d4f0cb08b3260ab2a852a39323d22abbf8e4a634

Add support for the same to synchronous machines. Awaitable machines require the same changes, but just a bit of monotonous work yet to be done to propagate them.

**Comment by prasannavl** [comment]
Latest pre-release should now cover it. Both Awaitable, and Synchronous state machines take an extra overload that provides you with `Transition<TState, TTrigger>`. Please let me know if this solves it.

**Comment by dandcg** [comment]
Perfect - nice one!
