### ISSUE TITLE
Could not build LiquidState project

### ISSUE THREAD

**Issue by anhdung28888** [prasannavl/LiquidState#24]
I cannot build LiquidState project due to syntax error when compiling.
I see that error happens at "=>" sign in struct InterlockedBlockingMonitor definition.
public bool IsBusy => Interlocked.CompareExchange(ref busy, -1, -1) > 0;

**Comment by prasannavl** [comment]
Hi. This is the new C# 6.0 syntax. I'm slowly moving to the new Roslyn based compiler. You may need to use the new set of compilers or use Visual Studio 2015.

**Comment by anhdung28888** [comment]
Could I install Roslyn compiler together with VS 2013?

**Comment by prasannavl** [comment]
Not entirely sure - Sorry. The best way is to install 2015, or to use the command line tools.
