### ISSUE TITLE
CanHandleTrigger() does not do correct compare.

### ISSUE THREAD

**Issue by keithballantyne** [prasannavl/LiquidState#4]
public bool CanHandleTrigger(TTrigger trigger)
        {
            foreach (var current in CurrentStateRepresentation.Triggers)
            {
                // is - if (current.Equals(trigger))
                // should be!
                if (current.Trigger.Equals(trigger))
                    return true;
            }

            return false;
        }

**Comment by prasannavl** [comment]
Nice catch! Thanks. 

Fixed by the commit https://github.com/prasannavl/LiquidState/commit/1255ed781d1d084f585e5bae7796e2d9077a84b6
