### ISSUE TITLE
CanHandleTrigger() does not check predicates.

### ISSUE THREAD

**Issue by keithballantyne** [prasannavl/LiquidState#6]
The CanHandleTrigger functions should check the predicates to determine if the proposed trigger will be honored.        

        public bool CanHandleTrigger(TTrigger trigger)
        {
            foreach (var current in CurrentStateRepresentation.Triggers)
            {
                if (current.Trigger.Equals(trigger))
                {
                    var predicate = current.ConditionalTriggerPredicate as Func<bool>;
                    if(predicate != null) 
                        return predicate();
                    else
                        return true;
                }
            }
            return false;
        }

**Comment by prasannavl** [comment]
I guess the consequences of delaying the unit tests are showing up. Thanks! Will release with the fix soon.

**Comment by prasannavl** [comment]
Fixed with the new version with breaking change: https://github.com/prasannavl/LiquidState/commit/04b65820666b641594810b27849087ea76ecebc1
